package sousuke.sousukeMod_main;

import cpw.mods.fml.common.ModMetadata;

public class S_Info {
	
	public static void loadInfo(ModMetadata meta) {
		
/*		meta.modId = sousuke_s_Mod.MODID;
		meta.name = .MODNAME;
		meta.description =".";
		meta.version =.VERSION ;
		meta.url = "";
*/
		meta.authorList.add("sousuke");
		meta.credits = "GregoriusT";
		meta.logoFile ="";
		meta.autogenerated = true;

	}
}
